[2025-03-19T15:40:01.290+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.load_news scheduled__2025-03-19T15:30:00+00:00 [queued]>
[2025-03-19T15:40:01.301+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.load_news scheduled__2025-03-19T15:30:00+00:00 [queued]>
[2025-03-19T15:40:01.301+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-19T15:40:01.302+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-03-19T15:40:01.302+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-19T15:40:01.324+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_news> on 2025-03-19 15:30:00+00:00
[2025-03-19T15:40:01.330+0000] {standard_task_runner.py:55} INFO - Started process 288 to run task
[2025-03-19T15:40:01.334+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tech_sentiment_pipeline', 'load_news', 'scheduled__2025-03-19T15:30:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmptr5zpwca']
[2025-03-19T15:40:01.336+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask load_news
[2025-03-19T15:40:01.429+0000] {task_command.py:389} INFO - Running <TaskInstance: tech_sentiment_pipeline.load_news scheduled__2025-03-19T15:30:00+00:00 [running]> on host 7408291b7a22
[2025-03-19T15:40:01.525+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tech_sentiment_pipeline
AIRFLOW_CTX_TASK_ID=load_news
AIRFLOW_CTX_EXECUTION_DATE=2025-03-19T15:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-19T15:30:00+00:00
[2025-03-19T15:40:01.538+0000] {base.py:73} INFO - Using connection ID 'mysql_default' for task execution.
[2025-03-19T15:40:02.467+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/example.py", line 112, in extract_transform_load_news
    news_data = extract_news_api_data()
  File "/opt/airflow/dags/example.py", line 66, in extract_news_api_data
    raise Exception(f"News API error: {response.status_code}")
Exception: News API error: 401
[2025-03-19T15:40:02.481+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=tech_sentiment_pipeline, task_id=load_news, execution_date=20250319T153000, start_date=20250319T154001, end_date=20250319T154002
[2025-03-19T15:40:02.510+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task load_news (News API error: 401; 288)
[2025-03-19T15:40:02.549+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-03-19T15:40:02.578+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:46:20.959+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.load_news scheduled__2025-03-19T15:30:00+00:00 [queued]>
[2025-03-19T15:46:20.969+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.load_news scheduled__2025-03-19T15:30:00+00:00 [queued]>
[2025-03-19T15:46:20.970+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-19T15:46:20.970+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-03-19T15:46:20.970+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-19T15:46:20.994+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_news> on 2025-03-19 15:30:00+00:00
[2025-03-19T15:46:21.004+0000] {standard_task_runner.py:55} INFO - Started process 213 to run task
[2025-03-19T15:46:21.010+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tech_sentiment_pipeline', 'load_news', 'scheduled__2025-03-19T15:30:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmp65ki5ww3']
[2025-03-19T15:46:21.012+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask load_news
[2025-03-19T15:46:21.100+0000] {task_command.py:389} INFO - Running <TaskInstance: tech_sentiment_pipeline.load_news scheduled__2025-03-19T15:30:00+00:00 [running]> on host 1c633b329d4d
[2025-03-19T15:46:21.413+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tech_sentiment_pipeline
AIRFLOW_CTX_TASK_ID=load_news
AIRFLOW_CTX_EXECUTION_DATE=2025-03-19T15:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-19T15:30:00+00:00
[2025-03-19T15:46:21.424+0000] {base.py:73} INFO - Using connection ID 'mysql_default' for task execution.
[2025-03-19T15:46:23.130+0000] {logging_mixin.py:137} INFO - News API: Fetched 100 articles.
[2025-03-19T15:46:24.253+0000] {logging_mixin.py:137} INFO - Hacker News: Fetched 100 stories.
[2025-03-19T15:46:24.367+0000] {logging_mixin.py:137} INFO - Inserted 200 records into sentiment_data table.
[2025-03-19T15:46:24.368+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-03-19T15:46:24.379+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=tech_sentiment_pipeline, task_id=load_news, execution_date=20250319T153000, start_date=20250319T154620, end_date=20250319T154624
[2025-03-19T15:46:24.429+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-03-19T15:46:24.459+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
